### ISSUE TITLE
BUILD FAILED in 48s 1 actionable task: 1 executed ERROR: Service 'tts' failed to build: The command '/bin/sh -c cat components.json | jq .[].artifact | xargs ./marytts insta

### ISSUE THREAD

**Issue by shriramhr** [codeforequity-at/botium-speech-processing#10]
Getting this error: 

BUILD FAILED in 48s
1 actionable task: 1 executed
ERROR: Service 'tts' failed to build: The command '/bin/sh -c cat components.json | jq .[].artifact | xargs ./marytts insta

**Comment by codeforequity-at** [comment]
hi, to overcome these build problems, i just published the prebuilt images on dockerhub. pls get the latest version of the repository, the docker-compose file now points to the prebuilt images.

**Comment by shriramhr** [comment]
> hi, to overcome these build problems, i just published the prebuilt images on dockerhub. pls get the latest version of the repository, the docker-compose file now points to the prebuilt images.

Thanks a ton.

**Comment by shriramhr** [comment]
@codeforequity-at it's working now, thanks a lot!
