### ISSUE TITLE
Cycling redirects

### ISSUE THREAD

**Issue by xSirrioNx** [codeforequity-at/botium-speech-processing#11]
Hi!
I'm trying to start botium in docker under nginx reverse proxy.
```
location / {
    	proxy_pass http://127.0.0.1:8008/;
        proxy_http_version 1.1;
		proxy_redirect off;
    }
```

But i have sycling redirects in Network tab of Chrome Dev Tools on any page
![image](https://user-images.githubusercontent.com/10046467/100147818-ebc8f380-2eac-11eb-86dc-a158eef3ea54.png)

Same issue on https://speech.botiumbox.com/ , https://speech.botiumbox.com/dictate, https://speech.botiumbox.com/tts

Also at page https://speech.botiumbox.com/tts
Try to click on any button
In Chrome console
```
tts:132 Uncaught ReferenceError: requestSynthesis is not defined
    at HTMLInputElement.onclick (tts:132)
```

**Comment by codeforequity-at** [comment]
working on it

**Comment by codeforequity-at** [comment]
fixed the issues in nginx.conf
